### ISSUE TITLE
喂养功能没有自定义词条

### ISSUE THREAD

**Issue by Dracl** [Hellobaka/KunBot#11]
```
「[无属性] 稳鲲 ★★★★★」体重增加了 1.89万 千克
现在体重 6.99万 千克
-------------------
剩余 55640 枚金币，4149 枚鲲蛋
```
快加！

**Comment by KuDikan** [comment]
也给以下词条添加自定义！
`Resurrect` 中的 `"，无法复活"`，
`Ranking` 中的 `"排行如下："`，
`Inventory` 中的 `"仓库为空"`，
`Devour` 与 `Attack` 中的 `"不能自己攻击自己"`

**`Kun.ToString()` 尤其是这个！**

**Comment by Hellobaka** [comment]
> **`Kun.ToString()` 尤其是这个！**

你期望鲲输出应当具有哪些自定义部分

**Comment by KuDikan** [comment]
> 你期望鲲输出应当具有哪些自定义部分

`PetAttributeA.Name` 、`PetAttributeB.Name`、`★★★`、`3★`、`词缀个数`

**Comment by Hellobaka** [comment]
> `PetAttributeA.Name` 、`PetAttributeB.Name`、`★★★`、`3★`、`词缀个数`

3星是什么 词缀个数固定为2

**Comment by KuDikan** [comment]
就是 `Level`+★或者直接 `Level`吧
词缀个数就是 `IPetAttribute.Description`那个的个数

**Comment by KuDikan** [comment]
`IPetAttribute.Description`好像是固定的？

**Comment by Hellobaka** [comment]
> 就是 `Level`+★或者直接 `Level`吧

可以改成配置，就目前需求来看没有做自定义的需要

> 词缀个数就是 IPetAttribute.Description那个的个数

感觉没摆出来的必要

**Comment by KuDikan** [comment]
> 可以改成配置，就目前需求来看没有做自定义的需要

目前等级没有上限，会出现★很长的情况
> 感觉没摆出来的必要 

这个就不要了

**Comment by Hellobaka** [comment]
5a24a2ce1e239bacd2e3ce3ccff313f73873a470
