### ISSUE TITLE
配置项ReplyFeed默认值异常

### ISSUE THREAD

**Issue by KuDikan** [Hellobaka/KunBot#18]
`\n` 少写了 `\`，`README.md` 里也写错了
![e00d7766a491bb71f97c2c045fc7e5ad](https://github.com/user-attachments/assets/ac6844fa-f2c7-4e61-aa2a-c92d84ec43b5)

**Comment by Hellobaka** [comment]
这种问题可以转成pr

**Comment by KuDikan** [comment]
好
