### ISSUE TITLE
反弹伤害词缀计算异常

### ISSUE THREAD

**Issue by KuDikan** [Hellobaka/KunBot#23]
`Jin.cs` 和 `Lei.cs` 对于反弹伤害的处理不一致
整理之后：
`Jin.cs`: `baseAttack = (1 + ((decrement - increment * change) / source), baseAttack.Item2);`
`Lei.cs`: `baseAttack = (1 + ((increment - decrement * (1+change))/ source), baseAttack.Item2);`

**Comment by Hellobaka** [comment]
总感觉都没错

**Comment by Hellobaka** [comment]
change = random(0.1, 0.3)
变化量 = increment - (decrement * change)
result = (1 + (变化量 / source), item2)
