### ISSUE TITLE
天劫系统匹配报错

### ISSUE THREAD

**Issue by Dracl** [Hellobaka/KunBot#29]
![image](https://github.com/user-attachments/assets/b7fe5efb-6b65-4e72-aa5b-d4f179f2fd32)
序列不包含任何匹配元素
   在 System.Linq.Enumerable.Last[TSource](IEnumerable`1 source, Func`2 predicate)
   在 Another_Mirai_Native.Protocol.OneBot.OneBotAPI.DispatchNotice(JObject notice)
   在 Another_Mirai_Native.Protocol.OneBot.OneBotAPI.HandleEvent(String data)

**Comment by Hellobaka** [comment]
协议层问题，与插件无关

**Comment by Hellobaka** [comment]
[54e3cfa](https://github.com/Hellobaka/Another-Mirai-Native2/commit/54e3cfa68263eaf5226d69c4c3a155c77855f09c)
