### ISSUE TITLE
鲲鲲排行榜问题和排行榜显示优化

### ISSUE THREAD

**Issue by Dracl** [Hellobaka/KunBot#30]
![image](https://github.com/user-attachments/assets/e35e1d3a-87d3-42ec-8e6e-a887dc5f1315)

排行榜没有跨群的鲲鲲，需修复（群里跟你说过的）

能否增加一个总排行榜？
输入排行榜指令，生成一个合并聊天记录，里面有本群和总排行榜
本群在前，总排行榜在后，两段消息，不知能否实现

```
第一段消息：本群(已有排行榜文案自定义)

1. [四季] [风] 菜虚鲲 ★★★★ 9965.58 吨
2. [四季] [无属性] 猛鲲 ★★★★ 7308.04 吨
3. [⁬⁬⁬⁫] [无属性] 贪鲲 ★★★ 416.59 吨
4. [菜虚鲲] [土] 牙鲲 ★★★★ 378.18 吨

第二段消息：总群(需要自定义文案~)

1. [四季] [风] 菜虚鲲 ★★★★ 9965.58 吨
2. [四季] [无属性] 猛鲲 ★★★★ 7308.04 吨
3. [⁬⁬⁬⁫] [无属性] 贪鲲 ★★★ 416.59 吨
4. [菜虚鲲] [土] 牙鲲 ★★★★ 378.18 吨
```

![image](https://github.com/user-attachments/assets/b7df651f-eaa3-46ff-9123-d403868d548c)
```
示例：
1. [四季] [风] 菜虚鲲 ★★★★ 9965.58 吨 [挂机中]
2. [四季] [无属性] 猛鲲 ★★★★ 7308.04 吨 [挂机中]
3. [⁬⁬⁬⁫] [无属性] 贪鲲 ★★★ 416.59 吨 [挂机中]
4. [菜虚鲲] [土] 牙鲲 ★★★★ 378.18 吨
```
能否在排行榜上显示是否在挂机？这样就不会无意义的攻击吞噬，需要自定义文案~

**Comment by Hellobaka** [comment]
无法生成合并聊天记录，将拆分成两个指令

**Comment by Hellobaka** [comment]
3a0089b1b3a6b9c07f24726d255435513d1ebefc
