### ISSUE TITLE
需求：增加一个挂机打工功能

### ISSUE THREAD

**Issue by Dracl** [Hellobaka/KunBot#31]
希望额外增加一个挂机功能，但是只是增加金钱，昨晚以后的农场功能的临时补救功能

因为金钱来源目前太单一了，只能签到获取，少了难玩，多了又会刚签到完就疯狂刷屏

如果用挂机获取的话，可以分摊每次游玩时间，不至于刷屏

希望可以 自定义文案 以及 每小时获取数量，我觉得一个固定的获取数量就好了，因为花钱的地方都是固定价格的

可以思考一下挂机打工要不要接入保护？

还是说打工的时候被攻击or吞噬可以爆一定比例金币？

到时候做的时候可以讨论一下 _(:3 」∠)_

**Comment by Dracl** [comment]
希望做打工的时候，给两个挂机功能都增加次数，每天只能进去三次，每天刷新次数

配置文案里增加一个变量，用来显示剩余次数

他们现在疯狂进出秘境不仅刷屏，还全程无敌，太耍赖了

每天签到渡劫然后就进秘境，差不多了就出来渡劫又进秘境！

**Comment by Hellobaka** [comment]
既然打工不被保护，如果在打工中被攻击会怎么样，会中断打工吗

**Comment by Hellobaka** [comment]
设计复杂，无法实现爆金币机制。
现阶段设计打工为无法打断。若因攻击而死亡，打工结算时会不给予金币
