### ISSUE TITLE
去除小数数值尾随零

### ISSUE THREAD

**Issue by KuDikan** [Hellobaka/KunBot#4]
.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00
.00将 `value.ToString("f2")` 改为 `value.ToString("0.##")`.00
.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00

**Comment by Hellobaka** [comment]
没什么道理，现阶段小数部分大多数情况下为0，是因为随机数精度不足
