### ISSUE TITLE
需求：能否做双词缀

### ISSUE THREAD

**Issue by Dracl** [Hellobaka/KunBot#42]
现在只有650种搭配，经常遇到重复的鲲鲲名字
如果是双词缀就有42250种，完全不可能重复了
要是太麻烦就算了，也不是什么特别刚需功能.jpg

**Comment by Hellobaka** [comment]
要实现也是两个小词缀 大词缀不能做两个

**Comment by Dracl** [comment]
> 要实现也是两个小词缀 大词缀不能做两个

对，我就是这个意思，双小词缀
[阴] 红红鲲 [阴] 红蓝鲲

**Comment by Hellobaka** [comment]
下下版本实现
