### ISSUE TITLE
需求：增加管理员指令

### ISSUE THREAD

**Issue by Dracl** [Hellobaka/KunBot#59]
![image](https://github.com/user-attachments/assets/2fb1f4c7-7015-4f39-8280-113467c7126d)

小兔崽子们天天互相攻击后体重小于0，让我复活，我每次要上服务器改数据库，太麻烦了

希望增加一个管理员强制复活指令，并且提供自定义指令，成功文案就不需要了发出了，直接复活就行

或者不复活，只是把体重改成正数，让他们自己用道具复活

这两个方案都可以，怎么方便怎么来

指令+ID

注意加个判断要把负号去掉，并且体重得是大于0，不然就会负数大危机_(:3 」∠)_
（负数被攻击吞噬，对方也会变成负数，然后传播开来整个存档就废了）

**Comment by Hellobaka** [comment]
为什么不能愿赌服输，不想做这个功能

**Comment by Dracl** [comment]
> 为什么不能愿赌服输，不想做这个功能

我也觉得，先搁置吧（
