### ISSUE TITLE
需求：能否给开盲盒加入冷却时间

### ISSUE THREAD

**Issue by Dracl** [Hellobaka/KunBot#65]
被刷到风控了，他们发现了每次开一个出货概率比直接开多个要高，一下午刷了几千个，bot直接风控无法发言了……

能否加入限制呢？

如果嫌麻烦就算，也不是特别刚需的功能，就个别人这样刷，我口头警告就行

加入的话，可以做成类似挂机的冷却提示一样，最好也提供自定义文案 红豆泥私密马赛

**Comment by Hellobaka** [comment]
感觉不如向群友宣讲单抽和多抽概率一样

**Comment by Hellobaka** [comment]
单抽和多抽的概率绝对是一样的
