### ISSUE TITLE
需求：世界BOSS!!!（草稿）

### ISSUE THREAD

**Issue by Dracl** [Hellobaka/KunBot#66]
### **_噔噔噔，最终机制！！世界BOSS！！_**

**添加指令：输入指令 获取介绍文案 和 BOSS介绍 下次刷新时间，类似天劫的介绍**

### 设定机制：
- 一条带特殊属性的世界BOSS级鲲鲲
- 默认等级直接拉满99吧，直接不考虑等级问题，目前吞噬和攻击机制也跟星级无关
- 直接从金木水火土风雷阴阳无十种属性里抽一个吧，每个10%概率
- 目前的设定是榜一大哥的X倍体重，每周刷新一条
- 如果是按周算的话，起码体重是榜单10倍起步了

（这boss是独立一个表，还是直接进kun表呢？（如果进kun表的话，可以无缝衔接攻击、吞噬、排行榜

### 名字机制：

- 金鳞耀世皇鲲：金鳞耀世，皇鲲镇宇，威震四海，睥睨天下。
- 苍梧古木灵鲲：苍梧古木，灵鲲参天，化身古树，守护万物。
- 寒渊潜涛冰鲲：寒渊深邃，冰鲲潜涛，静若幽潭，动如惊涛。
- 焚海烈焰炎鲲：焚海烈焰，炎鲲腾空，炽热如火，焚尽邪祟。
- 厚土守护灵鲲：厚土凝神，灵鲲守护，稳如磐石，护佑苍生。
- 风啸九天影鲲：风啸九天，影鲲无踪，疾如闪电，来去无痕。
- 雷霆万钧闪鲲：雷霆万钧，闪鲲降世，电光火石，震慑八荒。
- 幽冥游魂暗鲲：幽冥无尽，暗鲲游魂，行于阴影，摄人心魄。
- 赤阳辉煌圣鲲：赤阳辉煌，圣鲲照临，光耀四方，驱散黑暗。
- 虚无缥缈空鲲：虚无缥缈，空鲲无形，捉摸不定，迷惑众生。

金木水火土风雷阴阳无十种属性，直接套用原来的属性再加个00？
反正这个boss基本是沙包吧（

### 目前没想明白：
- 如何跟BOSS攻击、吞噬
- 是否让BOSS进排行榜 或 独立排行榜？
- 贡献率怎么算，是按次数还是按攻击的贡献
- 如何平衡一下让高等级不霸占所有的奖励（按次数好像就能解决这个问题）

### 奖励机制：
- 按照贡献率奖励高级盲盒
- 配置项限制上限，保底一个
- 像普通盲盒提供个自定义自己塞道具

### 惩罚机制：
1. 如果不杀死，全服鲲鲲掉 X% 体重（触发时）【支持正负】
2. 如果不杀死，全服鲲鲲掉 X 星（触发时）【支持正负】
3. 如果不杀死，全服背包掉 X% 金钱（触发时）【支持正负】
4. 如果不杀死，全服渡劫概率减少 X% 概率（全天生效）【支持正负】
5. 如果不杀死，全服商店价格增加 X%（全天生效）【支持正负】
6. 如果不杀死，全服探险or修炼减少 X% （全天生效）【支持正负】

感觉惩罚机制可以设置成支持正负数值的一个随机范围，正就是奖励，负就是惩罚，这样带数值的惩罚机制就翻倍了
（比如掉体重变成增加体重、变成增加星、增加金钱 玩法变得更多样但是机制不臃肿也不需要重复做
（等一个不知情的榜一吞掉奖励机制的boss然后挨骂

惩罚效果只生效一次就好了，那么奖励/惩罚应该什么时候生效呢？
（不然来了个掉星boss，直接生效直接掉星，那不是寄了

先暂定草稿，后面再编辑 _(:3 」∠)_

**Comment by Hellobaka** [comment]
- 一天一次太频繁，建议每月/每半月一次
- 需要给予世界boss机制，比如受到特定属性的鲲伤害翻倍之类的
- 禁用指令的惩罚不建议使用
- 给世界boss起点名字，提高辨识度

**Comment by Dracl** [comment]
> * 一天一次太频繁，建议每月/每半月一次
> * 需要给予世界boss机制，比如受到特定属性的鲲伤害翻倍之类的
> * 禁用指令的惩罚不建议使用
> * 给世界boss起点名字，提高辨识度

已修改成每周刷新，你看怎么样
套用原来的十属性再翻个倍就好了 减少工作量（
取消禁用指令惩罚
增加名字机制了

**Comment by Hellobaka** [comment]
not planned
